import type { ThemeConfig } from 'antd';
import tablerTokens from './tablerTokens';

const { colors, typography, radii, layout, elevation, spacing } = tablerTokens;

const tablerTheme: ThemeConfig = {
  token: {
    colorPrimary: colors.primary,
    colorPrimaryHover: colors.primaryHover,
    colorPrimaryActive: colors.primaryHover,
    colorSuccess: colors.success,
    colorWarning: colors.warning,
    colorError: colors.error,
    colorInfo: colors.info,
    colorLink: colors.primary,
    colorText: colors.text,
    colorTextSecondary: colors.textSecondary,
    colorTextTertiary: colors.textTertiary,
    colorTextQuaternary: colors.textTertiary,
    colorBorder: colors.border,
    colorBorderSecondary: colors.border,
    colorSplit: colors.border,
    colorBgLayout: colors.layout,
    colorBgContainer: colors.surface,
    colorFillAlter: colors.fillAlter,
    borderRadius: radii.control,
    borderRadiusSM: radii.sm,
    borderRadiusLG: radii.lg,
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSize,
    fontSizeSM: typography.fontSizeSM,
    fontSizeLG: typography.fontSizeLG,
    lineHeight: typography.lineHeight,
    controlHeight: layout.controlHeight,
    controlHeightSM: layout.controlHeightSM,
    controlHeightLG: layout.controlHeightLG,
    paddingXS: spacing.xs,
    paddingSM: spacing.sm,
    padding: spacing.md,
    paddingLG: spacing.lg,
    paddingXL: spacing.xl,
    boxShadow: elevation.raised,
    boxShadowSecondary: elevation.raised,
    boxShadowTertiary: elevation.raised,
  },
  components: {
    Layout: {
      bodyBg: colors.layout,
      headerBg: colors.surface,
      headerHeight: layout.headerHeight,
      headerPadding: `${spacing.none}px ${spacing.lg}px`,
      siderBg: colors.sider,
      triggerBg: colors.sider,
    },
    Menu: {
      darkItemBg: colors.sider,
      darkItemColor: colors.siderText,
      darkItemSelectedBg: colors.siderSelectedBg,
      darkItemSelectedColor: colors.textOnDark,
      itemBorderRadius: radii.control,
    },
    Card: { borderRadiusLG: radii.lg, boxShadow: elevation.flat },
    Table: {
      headerBg: colors.fillAlter,
      headerColor: colors.textSecondary,
      headerSplitColor: colors.border,
      borderColor: colors.border,
      rowHoverBg: colors.fillAlter,
      cellPaddingBlock: layout.tableCellPaddingBlock,
    },
    Button: { primaryShadow: elevation.flat, defaultShadow: elevation.flat },
    Select: {
      optionSelectedBg: colors.primarySelectedBg,
      optionActiveBg: colors.fillAlter,
      selectorBg: colors.surface,
      multipleSelectorBg: colors.surface,
      borderRadiusLG: radii.control,
    },
    Modal: { borderRadiusLG: radii.lg },
    Tag: { borderRadiusSM: radii.sm },
  },
};

export default tablerTheme;
