export const tablerTokens = {
  colors: {
    primary: '#066fd1',
    primaryHover: '#0559a8',
    success: '#2fb344',
    warning: '#f59f00',
    error: '#d63939',
    info: '#4299e1',
    text: '#232e3c',
    textSecondary: '#626976',
    textTertiary: '#959dac',
    border: '#e5e7eb',
    surface: '#ffffff',
    layout: '#f9fafb',
    fillAlter: 'rgba(35,46,60,0.02)',
    sider: '#182433',
    siderText: 'rgba(255,255,255,0.72)',
    siderSelectedBg: 'rgba(6,111,209,0.22)',
    textOnDark: '#ffffff',
    primarySelectedBg: 'rgba(6,111,209,0.09)',
    focusRing: 'rgba(6,111,209,0.18)',
  },
  spacing: { none: 0, xxs: 4, xs: 8, sm: 12, md: 16, lg: 24, xl: 32, xxl: 48 },
  typography: {
    fontFamily:
      "'Inter Var','Inter','Source Han Sans SC','Noto Sans SC','Source Han Sans CN','思源黑体',-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,'PingFang SC','Microsoft YaHei',sans-serif",
    fontSize: 14,
    lineHeight: 22 / 14,
    fontSizeSM: 12,
    fontSizeLG: 16,
    heading4: 20,
    heading3: 24,
  },
  radii: { sm: 4, control: 6, lg: 8, circle: 999 },
  layout: {
    headerHeight: 56,
    siderWidth: 200,
    siderCollapsedWidth: 80,
    contentMinPadding: 16,
    controlHeightSM: 24,
    controlHeight: 32,
    controlHeightLG: 40,
    tableCellPaddingBlock: 10,
  },
  elevation: {
    flat: 'none',
    raised: '0 2px 4px rgba(35,46,60,0.04)',
    raisedHover: '0 4px 10px rgba(35,46,60,0.08)',
  },
  motion: { fast: '150ms', normal: '200ms' },
  breakpoints: { mobile: 576, tablet: 768, desktop: 992, wide: 1200 },
  chart: {
    colors: ['#066fd1', '#2fb344', '#f59f00', '#d63939', '#4299e1', '#6f42c1'],
    axis: '#e5e7eb',
    label: '#626976',
    grid: '#eef0f2',
  },
} as const;

export const tablerCssVariables = {
  '--spm-color-primary': tablerTokens.colors.primary,
  '--spm-color-primary-hover': tablerTokens.colors.primaryHover,
  '--spm-color-success': tablerTokens.colors.success,
  '--spm-color-warning': tablerTokens.colors.warning,
  '--spm-color-error': tablerTokens.colors.error,
  '--spm-color-info': tablerTokens.colors.info,
  '--spm-color-text': tablerTokens.colors.text,
  '--spm-color-text-secondary': tablerTokens.colors.textSecondary,
  '--spm-color-text-tertiary': tablerTokens.colors.textTertiary,
  '--spm-color-border': tablerTokens.colors.border,
  '--spm-color-surface': tablerTokens.colors.surface,
  '--spm-color-layout': tablerTokens.colors.layout,
  '--spm-color-fill-alter': tablerTokens.colors.fillAlter,
  '--spm-color-sider': tablerTokens.colors.sider,
  '--spm-color-sider-text': tablerTokens.colors.siderText,
  '--spm-color-focus-ring': tablerTokens.colors.focusRing,
  '--spm-space-xs': `${tablerTokens.spacing.xs}px`,
  '--spm-space-sm': `${tablerTokens.spacing.sm}px`,
  '--spm-space-md': `${tablerTokens.spacing.md}px`,
  '--spm-space-lg': `${tablerTokens.spacing.lg}px`,
  '--spm-space-xl': `${tablerTokens.spacing.xl}px`,
  '--spm-radius-control': `${tablerTokens.radii.control}px`,
  '--spm-radius-card': `${tablerTokens.radii.lg}px`,
  '--spm-shadow-raised': tablerTokens.elevation.raised,
  '--spm-shadow-raised-hover': tablerTokens.elevation.raisedHover,
  '--spm-motion-fast': tablerTokens.motion.fast,
  '--spm-motion-normal': tablerTokens.motion.normal,
};

export default tablerTokens;
